name: Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: |
          npm install -g hexo-cli
          npm install
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          cname: blog.tonypepe.com
